name: BukkitExtras
version: 2.0
author: CodeNil
description: Small tweaks and changes for Bukkit

main: codednil.BukkitExtras.Main.BukkitExtras
softdepend: [BukkitProtect]


permissions:
	bukkitextras.*:
		description: Gives access to all BukkitExtras commands
		children:
			bukkitextras.modules.*: true
			bukkitextras.commands.*: true

	bukkitextras.modules.*:
		description: Allows access to all modules
		children:
			bukkitextras.modules.animaltweaks: true
			bukkitextras.modules.betterhoe.*: true
			bukkitextras.modules.shops.*: true
			bukkitextras.modules.wands.*: true

	bukkitextras.modules.animaltweaks:
		description: BukkitExtras Module "animaltweaks"
		default: true

	bukkitextras.modules.betterhoe.*:
		description: BukkitExtras Module "betterhoe"
		children:
			bukkitextras.modules.betterhoe.harvest: true
			bukkitextras.modules.betterhoe.grow: true
			bukkitextras.modules.betterhoe.plant: true
	bukkitextras.modules.betterhoe.harvest:
		description: BukkitExtras Module "betterhoe" Submodule "harvest"
		default: true
	bukkitextras.modules.betterhoe.grow:
		description: BukkitExtras Module "betterhoe" Submodule "grow"
		default: true
	bukkitextras.modules.betterhoe.plant:
		description: BukkitExtras Module "betterhoe" Submodule "plant"
		default: true

	bukkitextras.modules.shops.*:
		description: BukkitExtras Module "shops"
		children:
			bukkitextras.modules.shops.use: true
			bukkitextras.modules.shops.create: true
			bukkitextras.modules.shops.modifyothers: op
	bukkitextras.modules.shops.use:
		description: BukkitExtras Module "shops" Submodule "use"
		default: true
	bukkitextras.modules.shops.create:
		description: BukkitExtras Module "shops" Submodule "create"
		default: true
	bukkitextras.modules.shops.modifyothers:
		description: BukkitExtras Module "shops" Submodule "modifyothers"
		default: op

	bukkitextras.modules.wands.*:
		description: BukkitExtras Module "wands"
		children:
			bukkitextras.modules.wands.trading: true
	bukkitextras.modules.wands.trading:
		description: BukkitExtras Module "wands" Submodule "trading"
		default: true

	bukkitextras.commands.*:
		description: Allows access to all commands
		children:
			bukkitextras.commands.givewand: true

	bukkitextras.commands.givewand:
		description: BukkitExtras Command "givewand"
		default: op

commands:
	givewand:
		description: Give specified wand to player.
		usage: /<command> wand
		permission: bukkitextras.commands.givewand