name: BukkitExtras
main: io.github.CodedNil.BukkitExtras
version: D1.6
authors: [CodeNil, EliteJynx]
description: Small tweaks and addons for Bukkit
softdepend: [BukkitProtect]
permissions:
    bukkitextras.*:
        description: Gives access to all BukkitExtras commands
        children:
            bukkitextras.animaltags: true
            bukkitextras.betterhoes: true
            bukkitextras.specialhorses: true
            bukkitextras.elevators: true
            bukkitextras.wands: true
            bukkitextras.customenchants: true
            bukkitextras.givewand: true
            bukkitextras.shops: true
            bukkitextras.usefulanimals: true
            bukkitextras.enchantcustom: true
    bukkitextras.animaltags:
        description: Allows you to use AnimalTags
        default: true
    bukkitextras.betterhoes:
        description: Allows you to use all the Better Hoe features
        default: true
    bukkitextras.specialhorses:
        description: Allows you to convert your horse into a zombie/skeletal horse
        default: true
    bukkitextras.elevators:
        description: Allows you to use elevators
        default: true
    bukkitextras.wands:
        description: Allows you to use the wand of trading
        default: true
    bukkitextras.givewand:
        description: Allows you to use /givewand command
        default: op
    bukkitextras.enchantcustom:
        description: Allows you to use /enchantcustom command
        default: op
    bukkitextras.shops:
        description: Allows you to use shops
        default: true
    bukkitextras.usefulanimals:
        description: Allows you to get string from shearing sheep
        default: true
    bukkitextras.customenchant.*:
        description: Allows you to get custom enchants on your tools
        children:
            bukkitextras.fiery: true
            bukkitextras.feller: true
    bukkitextras.customenchant.fiery:
        description: Allows you to use the fiery enchant
        default: true
    bukkitextras.customenchant.feller:
        description: Allows you to use the feller enchant
        default: true
commands:
   givewand:
      description: Give specified wand to player.
      usage: /<command> wand
      permission: bukkitextras.givewand
   enchantcustom:
      description: Gives item in hand custom enchantment with level.
      usage: /<command> enchant level
      permission: bukkitextras.enchantcustom